# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8f33cf2725508549e3c2ba3d983c1ae263e3f1736878c723f40c0f9d047dcf0e87de4b880cb7792b3e28db9c7887a3ebb5f814f507ca066c93d2d1d4fda00307

test:
  secret_key_base: 495533f74ad5396adafdc9e3a6287bbc1d7ab55dab3deeeba6d26794536be121fb9593ae5d8e3f81d27d7425b966942eb1cfd53648930b8df99e3f3c23517ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
